title: "Datashare API Manager Role"
description: "Datashare API role to interface with GCP services"
stage: "GA"
includedPermissions:
- bigquery.datasets.create
- bigquery.datasets.delete
- bigquery.datasets.get
- bigquery.datasets.update
- bigquery.jobs.create
- bigquery.routines.create
- bigquery.routines.delete
- bigquery.routines.get
- bigquery.routines.update
- bigquery.tables.create
- bigquery.tables.delete
- bigquery.tables.export
- bigquery.tables.get
- bigquery.tables.getData
- bigquery.tables.getIamPolicy
- bigquery.tables.list
- bigquery.tables.setIamPolicy
- bigquery.tables.update
- bigquery.tables.updateData
- compute.projects.get
- firebaseauth.configs.create
- firebaseauth.configs.get
- firebaseauth.configs.getHashConfig
- firebaseauth.configs.update
- firebaseauth.users.create
- firebaseauth.users.createSession
- firebaseauth.users.delete
- firebaseauth.users.get
- firebaseauth.users.sendEmail
- firebaseauth.users.update
- iam.serviceAccounts.signBlob
- pubsub.subscriptions.consume
- pubsub.subscriptions.create
- pubsub.subscriptions.get
- pubsub.topics.attachSubscription
- pubsub.topics.create
- pubsub.topics.delete
- pubsub.topics.get
- pubsub.topics.getIamPolicy
- pubsub.topics.list
- pubsub.topics.setIamPolicy
- pubsub.topics.update
- resourcemanager.projects.get
- serviceusage.services.list
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.getIamPolicy
- storage.buckets.list
- storage.buckets.setIamPolicy
- storage.buckets.update
- storage.objects.create
- storage.objects.get
- storage.objects.list