---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dmc-listener-env-config
data:
  ## PROJECT_ID and TOPIC_NAME are only required for publisher
  #PROJECT_ID: "chrispage-dev"
  #TOPIC_NAME: "ds-multicast-demo-broadcast"
  ADDRESS: "239.0.0.1:50001"
  IF_NAME: "eth0"
  READ_BUFFER_BYTES: "5242880" # 5MB
  VERBOSE: "true"
